Feature: cache-bust image-set demos
Financial-Times/origami-registry pull request #67
Opened 2016-10-18 12:34 UTC by JakeChampion

This PR adds a new query parameter the the image-set demo img tag with the value of the current time in unix time format. This will act as a cache-buster to always show the latest image-set.

2016-10-18 12:35 UTC, JakeChampion commented
I tried to run this locally but always had PHP failures when running the `updateregistry` script.

2016-10-18 12:54 UTC, onishiweb commented
I'll run this locally tomorrow to test but looks good otherwise.

2016-11-01 11:27 UTC, rowanmanning requested changes

2016-11-01 11:27 UTC, rowanmanning commented on app/views/blocks/imageset-demo.html
> +					<img src="https://www.ft.com/__origami/service/image/v2/images/raw/{{imageset_scheme}}:{{image.name}}%3Fcache-bust%3D{{"now"|date("U")}}?source=origami-registry" alt="{{image.name}}" class="imag
Maybe this should use 10-minute intervals or something? So Cloudinary doesn't pull in millions of duplicate images.

2017-01-03 11:13 UTC, rowanmanning approved these changes

2017-01-03 11:14 UTC, merged